### ISSUE TITLE
Provide integration tests for the key functionalities

### ISSUE THREAD

**Issue by konstantina-gramatova** [eclipse-kanto/suite-bootstrapping#19]
The tests must cover the key component functionalities and use cases:
* TBD

**Comment by antonia-avramova** [comment]
**Prepare to start suite-connector service:**
- suite connector configuration file is backup
- suite bootstrapping service automatically sends the bootstrapping request
- prepare the new configuration file for suite connector with all mandatory registered resources
- prepare script to restart suite connector service after received the resources

**Suite connector service is up and running**
- create new feature in the created from suite-connector device

**Revert suite connector state**
- stop suite connector service
- restore saved backup configuration file of suite connector service
