### ISSUE TITLE
Improper message error sent when receiving a bootstrapping response with error

### ISSUE THREAD

**Issue by gabriela-yoncheva** [eclipse-kanto/suite-bootstrapping#22]
When receiving a bootstrapping response that contains an error, the bootstrapping service sends a message with status 204.

- when handling the bootstrapping response data, the message error value is missing

Instead the message should contain proper error message and status.

**Comment by e-grigorov** [comment]
The behavior seems correct. In this way, the bootstrapping just say I received and accepted the error response. Is there an issue with this?

**Comment by gabriela-yoncheva** [comment]
Since this behavior is expected, I'll be closing the issue.
